export const FETCH_QUIZES_START = `FETCH_QUIZES_START`;
export const FETCH_QUIZES_SUCCESS = `FETCH_QUIZES_SUCCESS`;
export const FETCH_QUIZES_ERROR = `FETCH_QUIZES_ERROR`;

export const FETCH_QUIZE_BY_ID_START = `FETCH_QUIZE_BY_ID_START`;
export const FETCH_QUIZE_BY_ID_SUCCESS = `FETCH_QUIZE_BY_ID_SUCCESS`;
export const FETCH_QUIZE_BY_ID_ERROR = `FETCH_QUIZE_BY_ID_ERROR`;

export const QUIZ_SET_STATE = `QUIZ_SET_STATE`;
export const FINISH_QUIZ = `FINISH_QUIZ`;
export const QUIZ_NEXT_QUESTION = `QUIZ_NEXT_QUESTION`;
export const RETRY_QUIZ = `RETRY_QUIZ`;
